baseURL = 'https://szydell.github.io/gtmdoc-mumps.pl/'
languageCode = 'en-us'
title = 'GT.M Documentation'
disablePathToLower = true

[module]
  [[module.imports]]
    path = "github.com/imfing/hextra"

[build]
  writeStats = true

[params]
  [params.navbar]
    displayLogo = true
  [params.footer]
    display = true
  [params.search]
    enable = true
    type = "flexsearch"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menus.main]]
  name = "theme"
  weight = 100
  [menus.main.params]
    type = "theme-toggle"
