name: Security Analysis

on:
  push:
    branches:
      - main
    paths:
      - '**/*.py'
      - '.github/workflows/security.yml'
  pull_request:
    branches:
      - main

jobs:
  bandit:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - name: Install git
        run: dnf install -y git

      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v3
          
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '>=3.10'
          
      - name: Code Security Analysis (Bandit)
        run: |
          uv tool install bandit
          uv tool run bandit -r .
